In [41]:
import random
import numpy as np

In [42]:
list = np.random.randint(0,10,20)

print(list)

[3 3 1 7 1 0 8 1 8 3 5 8 2 4 8 2 2 4 8 4]


In [43]:
list.sort()
print(list)

print(f"Smallest value is: {list[0]}, and the largest value is: {list[-1]}")

[0 1 1 1 2 2 2 3 3 3 4 4 4 5 7 8 8 8 8 8]
Smallest value is: 0, and the largest value is: 8


In [50]:
user_input = input("User Input: ")
count = 0
print(list)
for index in list:
    if user_input == list[index]:
        print("test")
        count += 1
print(f"The value {user_input} was found {count} times.")


[0 1 1 1 2 2 2 3 3 3 4 4 4 5 7 8 8 8 8 8]
The value 3 was found 0 times.
